version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=postgres-db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT = ${BE_PORT}

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=${FE_PORT}

  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5433:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
