# Use the official Node.js image as base
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which the Nest.js application will run
EXPOSE 3000

# Command to run the application with nodemon for automatic reloading
CMD ["npx", "nodemon", "--inspect=0.0.0.0:9229", "src/main.ts"]